# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  build-and-test:
    docker:
      - image: denoland/deno:1.18.2
    steps:
      - checkout
      - run: |
          deno test --allow-net test.ts

workflows:
  sample:
    jobs:
      - build-and-test